### PR TITLE
Fix incorrect duplicate file in Unrar.prototype.list

### PR DESCRIPTION
**Pull request by EricBabin**
With the rar file from the example below (output from `unrar vt -v`), I was getting 2 files when calling Unrar.prototype.list when I should have been getting just 1 file in the manifest. The submitted code change should fix this problem and handle the case where there might be the same file repeated more than once.

Example:
```
UNRAR 5.21 freeware      Copyright (c) 1993-2015 Alexander Roshal

Archive: test-rarfile.rar
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 848598540
 Packed size: 49999905
       Ratio: -->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: DBAA4372
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r00
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: 6D09E9F6
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r01
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: DC87389E
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r02
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: 779AD9E0
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r03
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: 6D9F2609
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r04
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: CC88C177
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r05
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: CC189460
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r06
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: DC3F2589
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r07
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: EC431088
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r08
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: 55C0EF4E
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r09
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: 48E64F76
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r10
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: 63E04DAC
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r11
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: 123A56C7
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r12
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: 3C1D02AA
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r13
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: 456A0F0F
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r14
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 2000000000
 Packed size: 49999905
       Ratio: <->
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
  Pack-CRC32: DD63A728
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M

Archive: test-rarfile.r15
Details: RAR 4, volume

        Name: test-rarfile.mkv
        Type: File
        Size: 848598540
 Packed size: 48600060
       Ratio: <--
       mtime: 2016-02-18 23:48:50,000
  Attributes: -rw-r--r--
       CRC32: F82AD279
     Host OS: Unix
 Compression: RAR 3.0(v20) -m0 -md=4M
```

As you can see in the example, the last instance has a ratio of "<--".

### CODE REVIEW

**Comment by burkostya** [comment]
Can you add the test?

**Comment by EricBabin** [comment]
My bad. I will add it shortly and submit updated code.

**Comment by EricBabin** [comment]
Test has been added.
I had to create a new test rar file since the one in my example was 800Mb.
Unfortunately, the test rar file seems to output the correct size on every volume but the code still works as expected. If anyone is able to generate a rar file with `Size` and `Packed Size` as in my first example output, then please feel free to add the file for testing.

**Comment by burkostya** [comment]
Thanks!

**Pull request merged**
